name: Test

on:
  push:
    branches: ['master']
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: ['master']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/checkout@v4
      - name: Install
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun lint
